#!/usr/bin/env bash

set -euo pipefail

declare tmpdir
tmpdir="$(mktemp -d)"

cleanup () {
    rm -fR "$tmpdir"
}

trap cleanup EXIT

mkdir -p "$tmpdir/cache"
# share fetchGit cache...
ln -s "$XDG_CACHE_HOME/nix" "$tmpdir/cache/nix"
export XDG_CACHE_HOME="$tmpdir/cache"

declare expr
expr="$(dirname "${BASH_SOURCE[0]}")/default.nix"

echo -n "Testing with an empty cache... " >&2
declare empty
empty="$(nix-instantiate --eval --read-write-mode \
             --allow-unsafe-native-code-during-evaluation \
             "$expr")"
echo "$empty" >&2
[ "$empty" = "\"success\"" ]

echo -n "Testing with an warm cache..." >&2
declare warm
warm="$(nix-instantiate --eval --read-write-mode \
            --allow-unsafe-native-code-during-evaluation \
            "$expr")"
echo "$warm" >&2
[ "$warm" = "\"success\"" ]
